---
GO_VERSION: "1.23.1"

APPLY_FIXES: none

SHOW_ELAPSED_TIME: true

ENABLE_LINTERS:
  - YAML_PRETTIER
  - YAML_YAMLLINT

  - GO_REVIVE
  - GO_GOLANGCI_LINT

  - MAKEFILE_CHECKMAKE

  - MARKDOWN_MARKDOWN_LINK_CHECK
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_REMARK_LINT

  - SQL_SQL_LINT
  - SQL_SQLFLUFF

  - MONGODB_MONGOSH

SQLFLUFF_DIALECT: postgres

JSON_REPORTER: true
FILEIO_REPORTER: false
EMAIL_REPORTER: false
FLAVOR_SUGGESTIONS: false
