sonar.organization=artventuria
sonar.projectKey=Artventuria_API

# This property is not mandatory but helps SonarCloud understand the project structure
sonar.sources=src/main/java
sonar.tests=src/test/java

# Encoding of the source code
sonar.sourceEncoding=UTF-8
