package com.artventuria.api.service.point.impl;

import com.artventuria.api.domain.postgresql.PointTransaction;
import com.artventuria.api.domain.postgresql.User;
import com.artventuria.api.exception.ResourceNotFoundException;
import com.artventuria.api.repository.jpa.points.PointTransactionRepository;
import com.artventuria.api.repository.jpa.user.UserRepository;
import com.artventuria.api.service.point.PointTransactionService;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import lombok.RequiredArgsConstructor;

import java.util.List;

@Service
@RequiredArgsConstructor
public class PointTransactionServiceImpl implements PointTransactionService {

    private final PointTransactionRepository pointTransactionRepository;
    private final UserRepository userRepository;

    @Override
    @Transactional
    public PointTransaction createTransaction(Integer userId, Integer points, String reason, Integer artworkId) {
        // Check if the user exists
        User user = userRepository.findById(userId)
                .orElseThrow(() -> new ResourceNotFoundException("User not found"));

        // Create the transaction
        PointTransaction transaction = new PointTransaction();
        transaction.setUserId(userId);
        transaction.setPoints(points);
        transaction.setDescription(reason);
        // Keep artworkId null if no artwork is associated - important for the DB
        // constraint
        if (artworkId != null && artworkId > 0) {
            transaction.setArtworkId(artworkId);
        } else {
            transaction.setArtworkId(null); // Ensure it's really NULL and not 0
        }
        transaction.setType(points >= 0 ? "EARN" : "SPEND");
        // Note: createdAt is automatically generated by @PrePersist

        // Update the user's total points
        user.setPoints(user.getPoints() + points);
        userRepository.save(user);

        // Save and return the transaction
        return pointTransactionRepository.save(transaction);
    }

    @Override
    @Transactional(readOnly = true)
    public List<PointTransaction> getUserTransactions(Integer userId) {
        return pointTransactionRepository.findByUserIdOrderByCreatedAtDesc(userId);
    }

    @Override
    @Transactional(readOnly = true)
    public Integer getUserBalance(Integer userId) {
        User user = userRepository.findById(userId)
                .orElseThrow(() -> new ResourceNotFoundException("User not found"));
        return user.getPoints();
    }
}
