name: Docker Release CI/CD

on:
  push:
    tags:
      - "v*" # Triggers only during version tag pushes (ex: v1.0, v1.1)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.2

      - name: Build Go binary with builder Dockerfile
        run: |
          docker build -f .deploy/builder.Dockerfile -t artventuria-builder .
          docker run --rm -v $PWD/build:/usr/src/app/build artventuria-builder

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/artventuria-api:${{ github.ref_name }} -f .deploy/Dockerfile .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/artventuria-api:${{ github.ref_name }}

      - name: Setup SSH with passphrase
        env:
          SSH_PASSPHRASE: ${{ secrets.SERVER_SSH_PASSPHRASE }}
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: |
          ssh-agent > ~/.ssh-agent-info
          . ~/.ssh-agent-info
          echo "echo $SSH_PASSPHRASE" > ~/.ssh_askpass && chmod +x ~/.ssh_askpass
          echo "$SSH_PRIVATE_KEY" | base64 -d | DISPLAY=None SSH_ASKPASS=~/.ssh_askpass ssh-add - >/dev/null

      - name: Deploy to Server
        run: |
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
          docker pull ${{ secrets.DOCKER_USERNAME }}/artventuria-api:${{ github.ref_name }}
          docker stop artventuria-api || true
          docker rm artventuria-api || true
          docker run -d --name artventuria-api -p 8000:7000 ${{ secrets.DOCKER_USERNAME }}/artventuria-api:${{ github.ref_name }}
