name: Docker Release CI/CD

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.2

      - name: Build Go binary
        run: |
          docker build -f .deploy/builder.Dockerfile -t artventuria-builder .
          docker run --rm -v $PWD/build:/usr/src/app/build artventuria-builder

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/artventuria-api:${{ github.ref_name }} -f .deploy/Dockerfile .

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/artventuria-api:${{ github.ref_name }}

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" | base64 -d > ~/.ssh/artventuria-key
          chmod 600 ~/.ssh/artventuria-key
          echo -e "Host ec2\n  HostName ${{ secrets.SERVER_HOST }}\n  User ec2-user\n  IdentityFile ~/.ssh/artventuria-key\n  StrictHostKeyChecking no" > ~/.ssh/config

      - name: Deploy to Server
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |
          ssh ec2 << EOF
            echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
            docker pull $DOCKER_USERNAME/artventuria-api:${GITHUB_REF_NAME}
          
            echo "Stopping and removing any existing container..."
            docker stop artventuria-api || true
            docker rm artventuria-api || true

            echo "Running the new container with restart policy..."
            docker run -d \
              --name artventuria-api \
              -p 8000:7000 \
              --restart unless-stopped \
              $DOCKER_USERNAME/artventuria-api:${GITHUB_REF_NAME}
          EOF
