name: Docker Release CI/CD

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.2

      - name: Build Go binary with builder Dockerfile
        run: |
          echo "Building Go binary..."
          docker build -f .deploy/builder.Dockerfile -t artventuria-builder .
          docker run --rm -v $PWD/build:/usr/src/app/build artventuria-builder

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t ${{ secrets.DOCKER_USERNAME }}/artventuria-api:${{ github.ref_name }} -f .deploy/Dockerfile .

      - name: Log in to Docker Hub
        run: |
          echo "Logging into Docker Hub..."
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          echo "Pushing Docker image to Docker Hub..."
          docker push ${{ secrets.DOCKER_USERNAME }}/artventuria-api:${{ github.ref_name }}

      - name: Configure SSH
        run: |
          echo "Configuring SSH with the provided private key..."
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" | base64 -d > ~/.ssh/artventuria-key
          chmod 600 ~/.ssh/artventuria-key
          
          # SSH config with verbose mode enabled
          echo -e "Host ec2\n  HostName ${{ secrets.SERVER_HOST }}\n  User ec2-user\n  IdentityFile ~/.ssh/artventuria-key\n  StrictHostKeyChecking no\n  LogLevel DEBUG3" > ~/.ssh/config

          # Debug: List SSH directory contents and permissions
          echo "Listing ~/.ssh contents and permissions:"
          ls -la ~/.ssh

      - name: Test SSH Connection
        run: |
          echo "Testing SSH connection with verbose output..."
          ssh -v ec2 "echo 'SSH connection successful'"

      - name: Deploy to Server
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |
          echo "Deploying to the server..."
          ssh ec2 << EOF
            echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
            docker pull $DOCKER_USERNAME/artventuria-api:${GITHUB_REF_NAME}
            docker stop artventuria-api || true
            docker rm artventuria-api || true
            docker run -d --name artventuria-api -p 8000:7000 $DOCKER_USERNAME/artventuria-api:${GITHUB_REF_NAME}
            echo "Container deployment completed."
            docker ps | grep artventuria-api
          EOF
