name: Docker Release CI/CD

on:
  push:
    tags:
      - "v*" # Triggers only during version tag pushes (ex: v1.0, v1.1)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.2

      - name: Build Go binary with builder Dockerfile
        run: |
          echo "Building Go binary with builder Dockerfile..."
          docker build -f .deploy/builder.Dockerfile -t artventuria-builder .
          docker run --rm -v $PWD/build:/usr/src/app/build artventuria-builder

      - name: Build Docker image
        run: |
          echo "Building Docker image for deployment..."
          docker build -t ${{ secrets.DOCKER_USERNAME }}/artventuria-api:${{ github.ref_name }} -f .deploy/Dockerfile .

      - name: Log in to Docker Hub
        run: |
          echo "Logging into Docker Hub..."
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          echo "Pushing Docker image to Docker Hub..."
          docker push ${{ secrets.DOCKER_USERNAME }}/artventuria-api:${{ github.ref_name }}

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" | base64 -d > ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key
          
          # Create SSH config file
          echo -e "Host ec2\n\tHostName ${{ secrets.SERVER_HOST }}\n\tUser ec2-user\n\tIdentityFile ~/.ssh/private_key\n\tStrictHostKeyChecking no" > ~/.ssh/config

      - name: Test SSH Connection
        run: ssh ec2 "echo 'SSH connection successful'"

      - name: Deploy to Server
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |
          ssh ec2 << EOF
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            docker pull ${{ secrets.DOCKER_USERNAME }}/artventuria-api:${GITHUB_REF_NAME}
          
            echo "Stopping and removing any existing container..."
            docker stop artventuria-api || true
            docker rm artventuria-api || true
          
            echo "Running the new container..."
            docker run -d \
              --name artventuria-api \
              -p 8000:7000 \
              --restart unless-stopped \
              ${{ secrets.DOCKER_USERNAME }}/artventuria-api:${GITHUB_REF_NAME}
          
            echo "Checking container status..."
            docker ps | grep artventuria-api
          EOF
