name: Docker Release CI/CD

on:
  push:
    tags:
      - 'v*'  # Triggers only during version tag pushes (ex: v1.0, v1.1)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Check out repository
        uses: actions/checkout@v4.2.2

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/artventuria-api:${{ github.ref_name }} -f .deploy/Dockerfile .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/artventuria-api:${{ github.ref_name }}

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
            docker pull ${{ secrets.DOCKER_USERNAME }}/artventuria-api:${{ github.ref_name }}
            docker stop artventuria-api || true
            docker rm artventuria-api || true
            docker run -d --name artventuria-api -p 7000:7000 ${{ secrets.DOCKER_USERNAME }}/artventuria-api:${{ github.ref_name }}
