name: Lint Pipeline

on:
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Check out code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Create Check Run
        id: create_check_run
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CHECK_RUN_ID=$(curl -s -X POST -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -d '{"name": "Lint Check", "head_sha": "${{ github.event.pull_request.head.sha }}", "status": "in_progress"}' \
            https://api.github.com/repos/${{ github.repository }}/check-runs | jq -r '.id')
          echo "CHECK_RUN_ID=$CHECK_RUN_ID" >> $GITHUB_ENV

      - name: Run MegaLinter
        id: lint
        uses: oxsecurity/megalinter@v8
        env:
          DEFAULT_BRANCH: develop
          GITHUB_STATUS_REPORTER: true
          GITHUB_STATUS_GH_API: true
          APPLY_FIXES: none
          SHOW_ELAPSED_TIME: true
          ENABLE_LINTERS: YAML_PRETTIER,YAML_YAMLLINT,GO_REVIVE,GO_GOLANGCI_LINT,MAKEFILE_CHECKMAKE,MARKDOWN_MARKDOWN_LINK_CHECK,MARKDOWN_MARKDOWN_TABLE_FORMATTER,MARKDOWN_MARKDOWNLINT,MARKDOWN_REMARK_LINT,SQL_SQL_LINT,SQL_SQLFLUFF,MONGODB_MONGOSH
          JSON_REPORTER: true
          FILEIO_REPORTER: false
          EMAIL_REPORTER: false
          FLAVOR_SUGGESTIONS: false

      - name: Complete Check Run
        if: ${{ steps.lint.outcome == 'success' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHECK_RUN_ID: ${{ env.CHECK_RUN_ID }}
        run: |
          curl -s -X PATCH -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -d '{"status": "completed", "conclusion": "success", "output": {"title": "Lint Check", "summary": "All linting checks passed successfully."}}' \
            https://api.github.com/repos/${{ github.repository }}/check-runs/$CHECK_RUN_ID

      - name: Complete Check Run with Failure
        if: ${{ steps.lint.outcome == 'failure' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHECK_RUN_ID: ${{ env.CHECK_RUN_ID }}
        run: |
          curl -s -X PATCH -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -d '{"status": "completed", "conclusion": "failure", "output": {"title": "Lint Check Failed", "summary": "Some linting checks did not pass. Please fix the issues and try again."}}' \
            https://api.github.com/repos/${{ github.repository }}/check-runs/$CHECK_RUN_ID
